var fs = require('fs');
var nodemailer = require('nodemailer');
var Server = require("mongo-sync").Server;
var server = new Server("localhost");
var db = server.db("exciting");
var sleep = require("sleep");

var transporter = nodemailer.createTransport({
  service: 'Hotmail',
  auth: {
    user: 'jesse.warren@live.com',
    pass: 'captaincrunch28!'
  }
});

function constructMessage(name, papers) {
  var text = name + ",</br></br>As part of a capstone course, we have built a pipeline for generating short summaries of academic papers from their in-text citations in other works. We want to evaluate the correctness and usefulness of the summaries generated by this pipeline.</br></br>The following " + (papers.length > 1 ? "links" : "link") + " will take you to a web form where you can evaluate the summaries generated by our pipeline for " + (papers.length > 1 ? "a few" : "one") + " of your most influential papers. We would greatly appreciate a few minutes of your time to fill out " + (papers.length > 0 ? "these evaluations" : "this evaluation") + ".</br></br>";

  papers.forEach(function(paper) {
    var link = "<a href='http://104.236.42.240:3000/email-response/?paper=" + paper.id + "'" + ">" + paper.title +"</a>";
    text += link + "</br>"
  });

  text += "</br>If you have any other feedback, questions or concerns, don't hesitate to contact us directly. Thanks again for your time!</br></br>" + "</br>Trevor Killeen</br>Graeme Britz</br>Jesse Warren</br>University of Washington Department of Computer Science";
  return text;
}

var seen = [];
var email_chunks = db.getCollection("emails").find().toArray();
//email_chunks.forEach(function(email_chunk) {
for (var i = 0; i <= 3; i++) {
  var email_chunk = email_chunks[i];
  var mailOptions = {
    from: 'Jesse Warren <jesse.warre@gmail.com>', // sender address
    to: 'jesse.warren@live.com', // list of receivers
    subject: 'Feedback requested for Information Extraction project at the University of Washington', // Subject line
    html: '<p>' + constructMessage(email_chunk.name, email_chunk.papers) + '</p>'
  };

  transporter.sendMail(mailOptions, function(error, info){
    if (error) {
      console.log(error);
    } else {
      console.log('Message sent: ' + info.response);
    }
    sleep.sleep(4);
  });
}

//});

server.close();
